### ISSUE TITLE
Running test.py issue

### ISSUE THREAD

**Issue by LizStan** [cnmodel/cnmodel#20] opened 2018-03-07 14:12 UTC
**I am having a problem with running the test.py in windows 10. I have followed the instructions for installing the CNmodel. However, when I run test.py in visual studio code via python in the terminal window this is what happens:**

 C:\Users\lizzy\Desktop\Masters Research\cnmodel-master> & C:/Users/lizzy/Anaconda2/python.exe "c:\Users\lizzy\Desktop\Masters Research\cnmodel-master\test.py"
NEURON -- VERSION 7.5 master (6b4c19f) 2017-09-25
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2016
See http://neuron.yale.edu/neuron/credits

loading membrane mechanisms from C:\Users\lizzy\Desktop\Masters Research\cnmodel-master\nrnmech.dll
Additional mechanisms from files
 CaPCalyx.mod Gly5GC.mod Gly5PL.mod Gly5State.mod Gly6S.mod Iclamp2.mod NMDA.mod NMDA_Kampa.mod ampa_trussell.mod bkpkj.mod cabpump.mod cadiff.mod cadyn.mod cap.mod capmp.mod capump.mod cleftXmtr.mod gly.mod gly2.mod hcno.mod hcno_bo.mod iStim.mod ihpkj.mod ihpyr.mod ihsgc_apical.mod ihsgc_basalmiddle.mod ihvcn.mod inav11.mod jsrnaf.mod ka.mod kcnq.mod kdpyr.mod kht.mod kif.mod kir.mod kis.mod klt.mod kpkj.mod kpkj2.mod kpkjslow.mod kpksk.mod leak.mod multisite.mod na.mod nacn.mod nacncoop.mod nap.mod napyr.mod pkjlk.mod rsg.mod vecevent.mod
Testing with flags: -v --tb=short cnmodel/
============================= test session starts =============================
platform win32 -- Python 2.7.14, pytest-3.3.2, py-1.5.2, pluggy-0.6.0 -- C:\Users\lizzy\Anaconda2\python.exe
cachedir: .cache
rootdir: C:\Users\lizzy\Desktop\Masters Research\cnmodel-master, inifile:
collected 36 items

cnmodel/an_model/tests/test_cache.py::test_cache

**Afterwhich, my Matlab command window opens up and the listed directory is CNmodel/Anmodel/model and hangs. No matlab file building performs as stated in the supporting documentation. If i type in the matlab command window run mexANmodel.m the mex is completed, and if i run ANmodel.m nothing happens as this matlab script is completely commented out. I then uncommented the vihc and model.synapse equation in the ANmodel.m file script and rerun ANmodel.m, but then i get an error as no inputs are provided. So I ask how do I get the model to run?**

**Comment by pbmanis** [comment] 2018-03-08 12:16
This occurs also on my Windows 10 partition (in parallels on a mac); it does not occur under Mac OSX. When running the main test.py tests, everything passes until it gets to testing Matlab, at which time a  Matlab console window appears (and is alive), but the program does not proceed further.
Meanwhile, I recommend that you install the "cochlea" model (from Rudnicki and Hemmert), which includes the Zilany et al. model; instructions for installing cochlea are in the README file. Cochlea does not require Matlab, and can run faster as the overhead for brining up an instance of Matlab is eliminated. This can be a significant savings in both time and memory if you are running parallel calculations, where each instance will bring up it's own copy of Matlab.
Note that some of the examples require that you specify the anmodel platform (e.g., as "matlab" or "cochlea"). 

I'll have to investigate the cause of this problem.

**Comment by pbmanis** [comment] 2018-03-09 00:03
I have investigated this a bit more. **I still recommend the "cochlea" model**, as it works with just a `pip install`, and is overall faster than bringing up Matlab to wrap the calculations.

However, (mostly for my own record), here are some issues, and where things stand on making this work (some of these are implemented in the Matlab branch, but see point 4).

1. In the Zilany c code (in the an_model/model subdirectory), the variable "outsize[2]" must be declared as: `size_t outsize[2];` instead of as `int`. (Done). Then `test_ANModel.m` succeeds after the mex compilation.
2. Mathworks provides an "engine" that can be imported into Python to run routines in Matlab. The routine` test_ANModel.py` in the same directory uses this engine to run test_ANModel.m (which now has to be declared as a function). This also succeeds. 
3. The current implementation uses a custom class "matlabprocess" in the file MatlabProc.py in the cnmodel/util subdirectory. This "pipes" text and data between the python and matlab processes. This works ok on OSX (with Matlab2017b) and Linux (older matlab versions), but does not appear to be working under Windows 10 with Matlab 2017b. I believe that the "matlabproc" code can be completely replaced using the (newer) matlab.engine, and at that point only be a few lines of code.  The selection of the models occurs (not so obviously) in `cache.py` routine, in the (more obviously named) generate_spiketrain function. The replacement to use the "engine" will involve replacing the functions in `wrapper.py` so that: getmatlab sets up the engine if it is not already set up; and so that the python code in model_iynapse and model_ihc in wrapper.py do their jobs seamlessly with the engine. The cost for this system-independence is likely to be speed, as the engine comes up more slowly than the old launch method.

I have created a new branch, 'matlab' to try out these changes in a staged manner; however this branch is in no way functional at this point.

**Comment by pbmanis** [comment] 2018-03-09 00:03
Whoops, that was supposed to keep the issue open, not close it.

**Comment by LizStan** [comment] 2018-03-09 08:26
Good day Paul,

Thank you very much for getting back to me about this issue, as I am considering to use this model as a comparison model for my Masters project, and it would be great if I had a functional model to compare my results against. I will work on your recommendations and give you some feedback with this regard and if I find a solution to the Matlab issue I will also let you know.

Regards
Liz

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by pbmanis** [comment] 2019-02-21 12:45
The issues with the matlab processes/engine should be now addressed in the Python3 branch. Please look at that branch and see if it works for you (you should create a new environment for python, update to the latest NEURON, and also follow the matlab instructions for installing the matlab.engine for python from Mathworks). At present, this appears to work under Windows for Python 3.6.4 and Matlab R2018b, at least on my test system. It also works under Mac OSX.

**Closed as completed** 2022-08-31 19:12 UTC
